### PR TITLE
Add alpine docker image version

### PR DESCRIPTION
**Pull request by rare-magma**
The alpine based php docker image results in a 5x reduction in image size when compared with the debian one (~125MB vs ~540MB)

### CODE REVIEW

**Comment by sstidl** [comment]
thank you very much for contributing @rare-magma 
i did look at the change but i cant see that you are creating the semver docker labels correctly.

the needed labels are
major
major.minor
major-alpine
major.minor-alpine
latest
latest-alpine

can you achive that?

**Comment by rare-magma** [comment]
@sstidl I've added the missing docker labels, could you please give it a try?

**Comment by sstidl** [comment]
@rare-magma i dont think i works as in your repo there are no tags matching the pattern. try to merge it in your master and make a release in your repo. then you should see something here: https://github.com/rare-magma/speedtest/pkgs/container/speedtest

**Comment by rare-magma** [comment]
@sstidl it seems to work fine:
```
podman pull ghcr.io/rare-magma/speedtest:latest ghcr.io/rare-magma/speedtest:latest-alpine
podman images | grep speedtest
ghcr.io/rare-magma/speedtest   latest         3a7ff00e3229  12 minutes ago  518 MB
ghcr.io/rare-magma/speedtest   latest-alpine  d903eb3d8174  16 minutes ago  120 MB
```

**Comment by sstidl** [comment]
Looks good. You tagged v999.999.999

**Comment by rare-magma** [comment]
@sstidl yes I created v999.999.999 as a test, I'll delete the fork and its packages later once this is merged

**Comment by sstidl** [comment]
The image building looks good now. Thank you!

I saw that you picked php8.2 in the Dockerfile for alpine. Is there a reason not to use 8.3 there?

**Comment by rare-magma** [comment]
@sstidl I've bumped it to 8.3 on https://github.com/librespeed/speedtest/pull/631/commits/76bb7de0378480dd51901c6ed883da98d5a957d4

**Review by sstidl — APPROVED** [review]

**Comment by sstidl** [comment]
@rare-magma thank you again for contributing. I just merged your changes.

We still need to add some documentation. 
I would appreciate if you could add something about the alpine flavour to the docker Readme. If you have time.

@adolfintel FYI

**Comment by adolfintel** [comment]
Yeah this looks absolutely fine :)

Sorry it took so long to merge it, thanks for your contribution.

**Pull request merged**
