### PR TITLE
fix ipinfo-db with old versions of PHP

### PR DESCRIPTION
**Pull request by IRainman**
This patch is returns the ability to do online check for IP location on older PHP versions.

### CODE REVIEW

**Comment by sstidl** [comment]
@IRainman If I read it correctly your patch disables the functionality completely?
what ist the problem with old versions of php? and how old is old?

**Comment by adolfintel** [comment]
When I implemented the offline DB feature I noticed that the maxmind db library required PHP 8. @sstidl initially suggested raising LibreSpeed to a minimum of 8.0, but I implemented a quick and dirty fallback for older versions because I know that there are servers running LS on really old systems.

From what I can see here, your PR here improves this workaround, but you really shouldn't rely on it. The newest version of 7.4 is from November 2022, you're putting yourself in danger by exposing it on the internet.

That being said, I'm ok with merging it if @sstidl agrees.

**Comment by sstidl** [comment]
Okay with me. As said before, php7 or even worse php5 is not supported anymore, so more security fixes there.

**Comment by IRainman** [comment]
Maybe this repo needs to clean up the support version of PHP for security reason #655

**Pull request merged**
