### PR TITLE
Enable privacy notice with docker variable

### PR DESCRIPTION
**Pull request by oalmlov**
Removes the `display:none` property on the privacy notice div when the user sets `ENABLE_PRIVACY_NOTICE` to true.

### CODE REVIEW

**Comment by adolfintel** [comment]
Thanks for the PR but I'm not sure I understand the point of this. The privacy notice is required only when telemetry is enabled, and that's what the current version does.

**Comment by oalmlov** [comment]
Hi,
I submitted the pull request because I am unable to get the privacy notice to be displayed when telemetry is set to `true`.

When i run the container using the command below the display attribute of the privacy notice DIV is still set to `none`.
`docker run -d -e MODE="standalone" -e TELEMETRY="true" -e PASSWORD="test123" -p 8080:80 -it adolfintel/speedtest`

Please close the PR if this is an error that's only happening to me.

**Comment by adolfintel** [comment]
That's strange. Can you check what happens here? https://github.com/librespeed/speedtest/blob/99edf0f5f440320fb23d222b3d56b172a61d32d3/docker/entrypoint.sh#L35

**Comment by oalmlov** [comment]
Made sure to pull the latest image and started a new container.
standalone.php is copied and db settings & telemetry password is inserted.


`root@xyz:[~] docker pull adolfintel/speedtest:latest
latest: Pulling from adolfintel/speedtest
Digest: sha256:90a2d1707c1181280e249fa53d1b49b6111499ad1a490c894384d0811fb7375e
Status: Image is up to date for adolfintel/speedtest:latest
docker.io/adolfintel/speedtest:latest

root@xyz:[~] docker run -d -e MODE="standalone" -e TELEMETRY="true" -e PASSWORD="test123" -p 8080:80 -it adolfintel/speedtest
4d94c7b9cee11a5176f767c8520ae252a92411a2b865c9dd9060915fd16be118

root@xyz:[~] docker logs 4d94
+ rm -rf '/var/www/html/*'
+ cp /speedtest/speedtest.js /speedtest/speedtest_worker.js /var/www/html/
+ '[' standalone == standalone ']'
+ cp -r /speedtest/backend/ /var/www/html/backend
+ '[' '!' -z '' ']'
+ '[' standalone == backend ']'
+ '[' standalone == frontend ']'
+ '[' standalone == standalone ']'
+ cp /speedtest/standalone.php /var/www/html/index.php
+ [[ true == \t\r\u\e ]]
+ [[ standalone == \f\r\o\n\t\e\n\d ]]
+ [[ standalone == \s\t\a\n\d\a\l\o\n\e ]]
+ cp -r /speedtest/results /var/www/html/results
+ sed -i 's/$db_type=".*"/$db_type="sqlite";/g' /var/www/html/results/telemetry_settings.php
+ sed -i 's/$Sqlite_db_file = ".*"/$Sqlite_db_file="\/database\/db.sql"/g' /var/www/html/results/telemetry_settings.php
+ sed -i 's/$stats_password=".*"/$stats_password="test123"/g' /var/www/html/results/telemetry_settings.php
+ '[' false == true ']'
+ '[' false == true ']'
+ mkdir -p /database/
+ chown www-data /database/
+ '[' 80 '!=' 80 ']'
+ echo 'Done, Starting APACHE'
Done, Starting APACHE
+ apache2-foreground
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.170.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.170.0.2. Set the 'ServerName' directive globally to suppress this message
[Thu Apr 23 09:41:24.312524 2020] [mpm_prefork:notice] [pid 17] AH00163: Apache/2.4.38 (Debian) PHP/7.2.29 configured -- resuming normal operations
[Thu Apr 23 09:41:24.312591 2020] [core:notice] [pid 17] AH00094: Command line: 'apache2 -D FOREGROUND'

root@xyz:[~] docker exec 4d94 sh -c "cat /var/www/html/index.php" | grep "^<div.*privacyPolicy"
<div id="privacyPolicy" style="display:none">`

**Comment by adolfintel** [comment]
That div is supposed to stay hidden, the PHP code in standalone.php just makes a link visible, and when that link is clicked it shows the privacy policy.
```
<?php if(getenv("TELEMETRY")=="true"){ ?>
        <a class="privacy" href="#" onclick="I('privacyPolicy').style.display=''">Privacy</a>
<?php } ?>
```

**Comment by oalmlov** [comment]
All right!
I thought I had looked for something like that but apparently not. 

I'll close the PR and focus on figuring out why our clients are acting like this. 
Thanks for the project by the way. Much appreciated.

**Comment by adolfintel** [comment]
No problem, let me know if you need help. Send me an URL to your test if you want me to take a look

**Pull request closed without merging**
