### PR TITLE
renamed .md files

### PR DESCRIPTION
**Pull request by SATYAM1548**
two files ending with .md extension had lower case name so I renamed it to upper case.

**Bug** https://github.com/librespeed/speedtest/issues/525

**Solved** renamed all .md files to upper case.

### CODE REVIEW

**Comment by Computroniks** [comment]
Not sure that this is neccessary. `README` is almost always capitalized. Generally, in pretty much every other repo I have seen, it is only `README`, `LICENCE`, `CODE_OF_CONDUCT` and `CONTRIBUTING` that are capitalized, all other `.md` files are left as lower case.

**Comment by SATYAM1548** [comment]
hello
@Computroniks 
Thanks for useful info ,I am  new to open source so I thought it can be a potential bug, really appreciate .

**Comment by 4yx** [comment]
> I am new to open source so I thought it can be a potential bug, really appreciate .

In general, it is good to assume there's no naming convention unless specifically mentioned so in the project.

**Comment by SATYAM1548** [comment]
> > I am new to open source so I thought it can be a potential bug, really appreciate .
> 
> In general, it is good to assume there's no naming convention unless specifically mentioned so in the project.

thanks !

**Review by Quentame — CHANGES_REQUESTED** [review]
This is not a rename but an addition.

Plus, this is not required, only some files are like `README` or `CONTRIBUTING` but for git servers/platforms to display the info (but maybe it also work lowercase).

**Comment by sstidl** [comment]
wont merge.

**Pull request closed without merging**
