### PR TITLE
Go backend implementation

### PR DESCRIPTION
**Pull request by maddie**
This is a complete port of the PHP backend to Go.

Speed tests, telemetry along with PNG generation, stats page are all implemented according to the PHP implementation, so it should be (almost) fully compatible with the original frontend.

Please let me know if there are any questions.

### CODE REVIEW

**Comment by adolfintel** [comment]
Looks good to me. Just a couple of questions:
* Do you have a demo that I can try?
* Would you be able to maintain this branch of the project? This mostly involves replying to issues and the occasional bug report

**Comment by maddie** [comment]
- I'll put up a demo soon. I'll let you know when I'm done.
- Yes, I will be able to maintain this branch as much as I can :)

**Comment by adolfintel** [comment]
Ok.
A couple more things:
* In the readme you said that you had to modify the worker because ispInfo wasn't of type object. This might be caused by HTTP headers, try investigating this further when you have time. It would be nice to fix that so that people can use PHP, Go and Node servers with the same frontend
* In the copyright notice, the GPL license requires that you add your name it instead of replacing mine. I would suggest something like Copyright 2020 Maddie Zhan, original version by Federico Dossena

**Comment by maddie** [comment]
Got it. I'll change it now.

**Comment by maddie** [comment]
- License fixed
- rawIspInfo object type fixed
- some other bugs fixed

Demo site: https://us1.zzz.cat/speedtest/

**Comment by adolfintel** [comment]
Looks really good to me, you really did a good job.
Just a couple more things:
* in getIP, the original version limits the accuracy to (if I remember correctly) 20km or 15mi
* The generated image is a bit low res, if you could increase it that would be great

Btw, I see that you're from China, if you don't mind, please write me at info@fdossena.com, I'd like to ask you a few questions.

**Comment by maddie** [comment]
I see it's `round(dist, -1)` in PHP, according to the documentation, I think that means round to nearest multiple of 10?

Of course, I will send you an email soon.

**Comment by adolfintel** [comment]
Yes, you're right, 20 and 15 were the lower limits

**Comment by adolfintel** [comment]
Thanks again for the awesome contribution to the project, I hope to have the time to keep it updated in the future as more features are added :)
I'll add you as a developer of the LibreSpeed organization.

**Pull request merged**
