### PR TITLE
(Node.js port) Added possibility to act as frontend and backend in Multiple test points mode

### PR DESCRIPTION
**Pull request by menemy**
Fixed node.js version to work as backend for multiple test points mode.
Added example of index.html to configure multiple points mode with node.js frontend.

### CODE REVIEW

**Comment by adolfintel** [comment]
@dunklesToast is the developer of the node branch. I'll let him be the judge on this PR

**Comment by dunklesToast** [comment]
LGTM but why have you changed all these `res.sendStatus(200); `?

**Comment by menemy** [comment]
sendStatus(200) returns status 200 with “OK” content but selectServer function want empty response.

https://github.com/librespeed/speedtest/blob/node/src/public/speedtest.js#L175

**Comment by dunklesToast** [comment]
Ok makes sense. I guess we can merge

**Pull request merged**
