### PR TITLE
Add BoltDB as embedded database option instead of SQLite

### PR DESCRIPTION
**Pull request by maddie**
There is not CGo-free SQLite implementation available, but it's not very portable for end-users if a PostgreSQL/MySQL database has to be deployed in order to enable telemetry.

I've added BoltDB as an alternative to SQLite for this purpose.

### CODE REVIEW

**Comment by adolfintel** [comment]
I didn't even know BoltDB existed, so I assume you know what you're doing.
I've added you to the LibreSpeed organization so you don't need to send PRs anymore, you can push to the go branch directly.

**Comment by maddie** [comment]
Ha, I see. I'll do so next time.

I've tested a bit with BoltDB and everything seems to work okay.

**Comment by adolfintel** [comment]
Add a page to the wiki with instructions on how to install and configure the Go version if you can

**Comment by maddie** [comment]
Sure, I'll write one soon.

**Pull request merged**
