### PR TITLE
Return the total amount of data volume used

### PR DESCRIPTION
**Pull request by berrnd**
Hi and first thanks a lot for LibreSpeed!

I wanted to show how much data volume the upload / download test used. So I've added 2 properties to the `speedtest_worker.js` status data object:
- `dlBytes`: Total number of bytes downloaded
- `ulBytes`: Total number of bytes uploaded

This also includes data during `dlGraceTime` / `ulGraceTime`.

Could look like that (a live example is available [here](https://speedtest.berrnd.net/)):

https://github.com/librespeed/speedtest/assets/2161815/4f761788-c76a-41cf-a8c1-454ee80d9268

### CODE REVIEW

**Comment by berrnd** [comment]
I guess this is bad and not working at all and therefore understand that it got closed without a single word of feedback. I'm deeply sorry for trying to to improve LibreSpeed, won't happen again.

**Comment by sstidl** [comment]
@berrnd im sorry, this was not intentional. i deleted the dev branch as it was confusing, this had the consequence that it deleted/closed all PRs in this branch.

**Comment by sstidl** [comment]
@berrnd could you please resubmit if you have the time? i tried to recover the changes but you had already deleted your fork

**Comment by berrnd** [comment]
> i deleted the dev branch as it was confusing, this had the consequence that it deleted/closed all PRs in this branch.

Didn't know that, without any further hint in the event timeline here this IMHO isn't very well thought out from GitHub - then sorry for my reaction, it just looked like that to me at first.

&nbsp;
> could you please resubmit if you have the time?

Restored my fork and resubmitted this PR: => #627

**Pull request closed without merging**
