### PR TITLE
Feature IPinfo offlinedb, preparation for 5.4

### PR DESCRIPTION
**Pull request by sstidl**

### CODE REVIEW

**Comment by adolfintel** [comment]
@sstidl I've updated the docker files. It seems to work locally, but I don't have a server running docker that I can test it on through the internet right now. I'm mostly concerned about getIP, I can't test that properly locally. Can you give it a go?

**Comment by sstidl** [comment]
Test was ok. I didnt find how to see dark mode but location works with local db and api key 

Can you read through 
https://github.com/librespeed/speedtest/blob/ipinfo_offlinedb/doc_docker.md
and add the parts about the local db?

I can't do it right now.

**Comment by adolfintel** [comment]
Done, I accidentally pushed a small fix to docker/ui.php along with the readme. Not the best git hygene, I know, but we're going to squash these commits anyway.

**Comment by adolfintel** [comment]
I just did some testing and the inclusion of the mmdb library raised the minimum PHP version 8.0, I'll see if I can make it optional.

**Comment by adolfintel** [comment]
I've added some fallback code in getIP. If you have a version of PHP <8 it only gives you the IP address.

**Comment by sstidl** [comment]
> I've added some fallback code in getIP. If you have a version of PHP <8 it only gives you the IP address.

As PHP<8 is not supported anymore I don't think it's good to signalize we support anything that low
https://www.php.net/supported-versions.php

**Comment by adolfintel** [comment]
So, I did a bit more testing yesterday and I'd say 5.4 is ready to go.

Before I make the release I want to update the quickstart videos, since they've been obsolete for a few years now, and make them for both debian and a generic docker install. I'll make these today.

I haven't tested the mssql database since that came in from a PR and I don't have a windows server machine. Do you have something to test this on @sstidl ?

As for the minimum PHP version, I'd agree with you but I've already done the fallback code and I know for a fact that we have some backend servers (not under my control) that regularly pull updates from this repo and use PHP 7, and I don't want to break them (yet).

I'll also get rid of the current wiki since it has the same stuff as doc.md and doc_docker.md

**Comment by sstidl** [comment]
I don't have easy access to an mssql server so, no can't test it at the moment. Maybe we just write that in the Readme that mssql is untested.
I would also like to look over the docker related md files before release so please wait for me.

**Comment by adolfintel** [comment]
I updated the quick start video, I'm ready when you are @sstidl

**Comment by sstidl** [comment]
@adolfintel please look over the changes to the *.md files i did... i tried to reduce redundancy and described how to use other dbs in docker scenario. i didnt have the time to test a docker deployment with an external db so this still need more detail. anyway I think we have good reason to release :-)

**Comment by adolfintel** [comment]
The changes in the documentation look good to me.

I didn't test all the external databases, only the sqlite one since it required no configuration, and it worked. The code seems straightforward enough though, I doubt it will give us issues.

I'll release 5.4 tomorrow morning.

**Comment by sstidl** [comment]
@adolfintel thank you for the release. Please always use versions with 3 parts. My docker build workflow depends on it. So I changed the release to 5.4.0 and tagged 5.4.0. 
Restarted the workflow now

**Comment by adolfintel** [comment]
Yeah I just noticed the problem about semver. This project never strictly followed that standard :sweat_smile: , I'll have to be more careful

**Comment by adolfintel** [comment]
By the way, if you have time, there are a bunch of issues and PRs that can be closed as they're no longer relevant. This project really needs a cleanup before work on 6.0 can start.

**Comment by sstidl** [comment]
> Yeah I just noticed the problem about semver. This project never strictly followed that standard 😅 , I'll have to be more careful

Unfortunately the workflow still fails. Don't know how to trigger a corrected run so the docker images with the correct tags are built.



> By the way, if you have time, there are a bunch of issues and PRs that can be closed as they're no longer relevant. This project really needs a cleanup before work on 6.0 can start.

My vacation ends today so I don't think I can afford some time in the next week. Maybe next weekend.

**Comment by adolfintel** [comment]
There's no rush, we can do it when we have time. I'll start working again in a few days as well.

I'll take a look at the failed workflow and see what I can do.

**Comment by adolfintel** [comment]
I had to redo the release. I tried modifying docker-publish.yml to add the workflow_dispatch event so I could trigger it manually but it didn't want to trigger on the 5.4.0 tag again so I just deleted the release, the 5.4 and 5.4.0 tags and recreated them.

**Comment by jk779** [comment]
Hi guys,

i've been a very bad boy and have been overwriting standalone.php in my docker-compose.yml to add some deep customizations.

I now realize that this was a bad idea :/ Any quick recommendations on how to easily migrate my standalone.php "fork" to the new structure? I'm not even sure what the right file location would be and i'm not too keen on reimplementing the changes to a more sophistocated and correct way because of no time 🙈 and on top of that i didn'teven use a version control to retrace my steps 🌚

**Comment by sstidl** [comment]
@jk779 please don't use a closed pull request for issues. I created a new issue for you.

**Pull request merged**
